import assert from "node:assert/strict";
import test from "node:test";
import {
  buildVisualPageSections,
  cleanTruncatedText,
  extractCleanBullets,
  extractShortCompleteBullets,
  fitCompleteSentenceOnly,
  fitCompleteWordsOnly,
  fitLinesWithoutEllipsis,
  fitTextWithoutEllipsis,
  getVisualTemplate,
  isComicProject,
  isEditorialVisualProject,
  isNotebookReflectionProject,
  resolveEditorialLayout,
  removeVisibleEllipsis,
  shortenToCompletePhrase,
  visualBodyTypography,
} from "../app/visual-book-exporters";
import { normalizeVisualPages } from "../app/visual-book-utils";
test("visual storyboard normalization enforces the requested page count and roles",()=>{const p=normalizeVisualPages([{title:"Cover",body:"Hook",image_prompt:"A door",layout:"full-bleed"}],5,"visual");assert.equal(p.length,5);assert.equal(p[0].role,"cover");assert.equal(p[4].role,"cta");assert.deepEqual(p.map(x=>x.pageNumber),[1,2,3,4,5]);assert.equal(p[0].panels.length,0)});
test("comic storyboard normalization creates bounded editable panels",()=>{const p=normalizeVisualPages([{title:"Cover",panel_count:1,panels:[{scene:"Two rivals",dialogue:[]}]},{title:"Impact",panel_count:8,panels:[{scene:"A glass falls",camera:"Close-up",dialogue:[{speaker:"Mara",text:"Don't move."}],caption:"Too late.",sound_effect:"CRASH!"}]}],5,"comic");assert.equal(p[0].panels.length,1);assert.equal(p[1].panels.length,4);assert.equal(p[1].panels[0].dialogue[0].speaker,"Mara");assert.equal(p[1].panels[0].soundEffect,"CRASH!")});
test("visual export routing uses only the explicit project mode",()=>{assert.equal(isComicProject({mode:"comic"}),true);assert.equal(isComicProject({mode:"visual"}),false);assert.equal(isEditorialVisualProject({mode:"visual"}),true)});
test("editorial layout fallback never selects a comic layout",()=>{assert.equal(resolveEditorialLayout({role:"cover",pageNumber:1}),"full-bleed");assert.equal(resolveEditorialLayout({role:"content",pageNumber:2}),"image-top");assert.equal(resolveEditorialLayout({role:"content",pageNumber:3}),"image-left");assert.equal(resolveEditorialLayout({role:"cta",pageNumber:7}),"quote")});
test("notebook reflection routing accepts safe template aliases only for visual projects",()=>{const visual={mode:"visual",visualStyle:"notebook-reflection"} as unknown as import("../app/visual-book-types").VisualBookProject;const legacy={mode:"visual",visualStyle:"cinematic-editorial",template:"notebook-reflection"} as unknown as import("../app/visual-book-types").VisualBookProject;const comic={mode:"comic",visualStyle:"notebook-reflection"} as unknown as import("../app/visual-book-types").VisualBookProject;assert.equal(getVisualTemplate(visual),"notebook-reflection");assert.equal(getVisualTemplate(legacy),"notebook-reflection");assert.equal(isNotebookReflectionProject(visual),true);assert.equal(isNotebookReflectionProject(legacy),true);assert.equal(isNotebookReflectionProject(comic),false)});
test("visual page sections keep the full body and fill supporting areas only with source-derived meaning",()=>{const source="The garden changes slowly. Mika notices each new leaf. Patience makes the blue visible. Attention becomes a daily practice.";const sections=buildVisualPageSections(source,"The Garden");assert.equal(sections.body,source);assert.deepEqual(sections.highlights,["Patience makes the blue visible.","Attention becomes a daily practice."]);assert.equal(sections.note,"The garden changes slowly.");const short=buildVisualPageSections("One honest lesson.","Lesson");assert.equal(short.body,"One honest lesson.");assert.deepEqual(short.highlights,["One honest lesson."])});
test("visual copy cleanup drops chopped trailing fragments and keeps complete phrases",()=>{assert.equal(cleanTruncatedText("The lesson is complete. The garden answe..."),"The lesson is complete.");assert.equal(cleanTruncatedText("The field note… becomes clear."),"The field note becomes clear.");assert.equal(removeVisibleEllipsis("Mika waits for a..."),"");const shortened=shortenToCompletePhrase("Attention grows slowly, but the most useful part of the lesson needs much more space than the takeaway card can provide.",64);assert.equal(shortened,"Attention grows slowly.");assert.doesNotMatch(shortened,/(?:\.{3}|…)/)});
test("visual bullet extraction prefers short complete source-derived sentences",()=>{const source="The garden changes slowly. Mika notices each new leaf without rushing the season or forcing the result. Patience makes the blue visible. Attention becomes a daily practice.";const bullets=extractCleanBullets(source,3,52);assert.equal(bullets.length,3);for(const bullet of bullets){assert.doesNotMatch(bullet,/(?:\.{3}|…)/);assert.match(bullet,/[.!?]$/);assert.ok(source.includes(bullet)||bullet.length<=53)}});
test("visual text fitting reduces type or stops at a complete sentence without drawing ellipses",()=>{const drawn:string[]=[];const context={font:"",measureText(this:{font:string},value:string){const size=Number(/(\d+)px/.exec(this.font)?.[1]||20);return{width:value.length*size*.56}},fillText(value:string){drawn.push(value)}} as unknown as CanvasRenderingContext2D;const fitted=fitTextWithoutEllipsis(context,"The first thought is complete. The second thought is deliberately much too long to fit inside the allotted line budget without being clipped.",{x:0,y:20,maxWidth:210,maxLines:2,fontSize:24,minFontSize:20,lineHeight:30,fontFamily:"Arial"});assert.equal(fitted.text,"The first thought is complete.");assert.ok(fitted.lines.length<=2);assert.doesNotMatch(drawn.join(" "),/(?:\.{3}|…)/)});
test("visual safe-fitting helpers hard-ban ellipsis and chopped source fragments",()=>{const context={font:"20px Arial",measureText(value:string){return{width:value.length*10}}} as unknown as CanvasRenderingContext2D;const source="Patience makes the blue visible. Mika waits for the answe...";const sentence=fitCompleteSentenceOnly("The cover grows through a...",source);const words=fitCompleteWordsOnly(context,"Whole words stay readable even when the final fragment ca...",180,2);const lines=fitLinesWithoutEllipsis(context,source,240,2);const bullets=extractShortCompleteBullets("Attention becomes a practice. The garden wo...",3,80);for(const value of [sentence,words,...lines,...bullets]){assert.doesNotMatch(value,/(?:\.{3}|…)/);assert.doesNotMatch(value,/\b(?:answe|ca|wo)[.!?]?$/)}assert.equal(sentence,"Patience makes the blue visible.");assert.deepEqual(bullets,["Attention becomes a practice."])});
test("visual body typography becomes denser without changing comic routing",()=>{const short=visualBodyTypography("brief useful copy");const long=visualBodyTypography(Array.from({length:140},()=>"meaningful").join(" "));const narrow=visualBodyTypography(Array.from({length:120},()=>"meaningful").join(" "),true);assert.ok(long.fontSize<short.fontSize);assert.ok(long.maxLines>short.maxLines);assert.equal(narrow.maxLines,16);assert.equal(isComicProject({mode:"comic"}),true)});
