"use client";
import { BookOpen, Check, ChevronDown, ChevronUp, Download, FileImage, FileText, Image as ImageIcon, LayoutGrid, LoaderCircle, MessageCircle, Plus, RotateCcw, Save, Sparkles, Trash2 } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import type { ActiveAIProvider, AIProvider } from "./book-types";
import { COMIC_FORMATS, VISUAL_BOOK_KINDS, VISUAL_STYLES, blankVisualBookBrief, type ComicPanel, type VisualBookBrief, type VisualBookPage, type VisualBookProject, type VisualPageCount, type VisualProjectMode } from "./visual-book-types";
import { normalizeVisualPages } from "./visual-book-utils";
import { exportVisualPageJpeg, exportVisualPagesZip, exportVisualPdf } from "./visual-book-exporters";
import { deleteVisualProject, loadVisualProjects, saveVisualProject } from "./visual-book-storage";
import { deleteCloudProject, saveCloudProject, syncCloudProjects, type SyncState } from "./cloud-library-client";
type Busy = "" | "storyboard" | "page" | "image" | "all-images" | "pdf" | "zip";

export default function VisualBookStudio({ provider }: { provider: AIProvider }) {
  const [mode,setMode]=useState<VisualProjectMode>("visual"), [brief,setBrief]=useState<VisualBookBrief>(()=>blankVisualBookBrief("visual"));
  const [project,setProject]=useState<VisualBookProject|null>(null), [projects,setProjects]=useState<VisualBookProject[]>([]), [activePage,setActivePage]=useState(0);
  const [busy,setBusy]=useState<Busy>(""), [busyTarget,setBusyTarget]=useState(""), [error,setError]=useState(""), [notice,setNotice]=useState("");
  const [syncState,setSyncState]=useState<SyncState>("syncing");
  const page=project?.pages[activePage]??null, locked=Boolean(busy);
  useEffect(()=>{let dead=false;void loadVisualProjects().then(async local=>{const synced=await syncCloudProjects("visual",local);if(dead)return;setProjects(synced.projects);setSyncState(synced.state);await Promise.all(synced.projects.map(saveVisualProject))}).catch(()=>{if(!dead)setError("Saved visual projects could not be loaded from this browser.")});return()=>{dead=true}},[]);
  useEffect(()=>{if(!project)return;const t=window.setTimeout(()=>{void saveVisualProject(project).then(()=>setProjects(c=>[project,...c.filter(x=>x.id!==project.id)].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)))).catch(()=>setError("This browser could not save the latest visual project changes."));void saveCloudProject("visual",project).then(()=>setSyncState("synced")).catch(()=>setSyncState("local-only"))},650);return()=>window.clearTimeout(t)},[project]);
  const imageProgress=useMemo(()=>{if(!project)return{complete:0,total:0};if(project.mode==="comic"){const p=project.pages.flatMap(x=>x.panels);return{complete:p.filter(x=>x.imageData).length,total:p.length}}return{complete:project.pages.filter(x=>x.imageData).length,total:project.pages.length}},[project]);
  function chooseMode(next:VisualProjectMode){if(locked||next===mode)return;setMode(next);setBrief(blankVisualBookBrief(next));setProject(null);setActivePage(0);setError("");setNotice("")}
  function updateBrief<K extends keyof VisualBookBrief>(k:K,v:VisualBookBrief[K]){setBrief(c=>({...c,[k]:v}))}
  function updateProjectBrief<K extends keyof VisualBookBrief>(k:K,v:VisualBookBrief[K]){setBrief(c=>({...c,[k]:v}));setProject(c=>c?{...c,[k]:v,updatedAt:new Date().toISOString()}:c)}
  function reset(){setProject(null);setBrief(blankVisualBookBrief(mode));setActivePage(0);setError("");setNotice("")}
  async function createStoryboard(e:FormEvent){e.preventDefault();if(!brief.title.trim()||!brief.author.trim()||!brief.premise.trim()){setError("Add the title, author, and story idea or core promise first.");return}setBusy("storyboard");setError("");setNotice("");try{const data=await api("/api/generate",{action:"visual_storyboard",mode:"fiction",brief:{title:brief.title},provider,visualProject:brief});const now=new Date().toISOString(),b={...brief,subtitle:brief.subtitle.trim()||String(data.refined_subtitle??"").trim(),characterBible:brief.characterBible.trim()||String(data.character_bible??"").trim(),palette:brief.palette.trim()||String(data.palette??"").trim()};const next:VisualBookProject={...b,id:project?.id??crypto.randomUUID(),createdAt:project?.createdAt??now,updatedAt:now,pages:normalizeVisualPages(data.pages,b.pageCount,b.mode),providersUsed:data.provider?[data.provider as ActiveAIProvider]:[]};setBrief(b);setProject(next);setActivePage(0);setNotice("Storyboard ready. Review the pages and character lock before generating images.")}catch(x){setError(message(x,"The visual storyboard could not be created."))}finally{setBusy("")}}
  function updatePage(patch:Partial<VisualBookPage>){if(!project||!page)return;setProject({...project,pages:project.pages.map((x,i)=>i===activePage?{...x,...patch}:x),updatedAt:new Date().toISOString()})}
  function updatePanel(i:number,patch:Partial<ComicPanel>){if(!page)return;updatePage({panels:page.panels.map((x,n)=>n===i?{...x,...patch}:x)})}
  function addPanel(){if(!page||page.panels.length>=4)return;updatePage({panels:[...page.panels,{id:`panel-${crypto.randomUUID()}`,order:page.panels.length+1,scene:"",camera:"medium cinematic composition",dialogue:[],caption:"",soundEffect:""}]})}
  function removePanel(i:number){if(!page||page.panels.length<=1)return;updatePage({panels:page.panels.filter((_,n)=>n!==i).map((x,n)=>({...x,order:n+1}))})}
  function addDialogue(i:number){if(!page)return;updatePanel(i,{dialogue:[...page.panels[i].dialogue,{speaker:"",text:""}].slice(0,3)})}
  function updateDialogue(pi:number,di:number,k:"speaker"|"text",v:string){if(!page)return;updatePanel(pi,{dialogue:page.panels[pi].dialogue.map((x,n)=>n===di?{...x,[k]:v}:x)})}
  function removeDialogue(pi:number,di:number){if(!page)return;updatePanel(pi,{dialogue:page.panels[pi].dialogue.filter((_,n)=>n!==di)})}
  async function rewrite(){if(!project||!page)return;setBusy("page");setError("");try{const data=await api("/api/generate",{action:"visual_page",mode:"fiction",brief:{title:project.title},provider,preferredProvider:project.providersUsed?.at(-1),visualProject:{...project,page}});const p=normalizeVisualPages([data.page],1,project.mode)[0];updatePage({...p,id:page.id,pageNumber:page.pageNumber,role:page.role,panels:p.panels.map((x,i)=>({...x,imageData:page.panels[i]?.imageData}))});setNotice(`Page ${page.pageNumber} was rewritten. Existing art stays until you regenerate it.`)}catch(x){setError(message(x,"This page could not be rewritten."))}finally{setBusy("")}}
  async function generateImage(pageIndex:number,panelIndex?:number){if(!project)return;const p=project.pages[pageIndex],panel=typeof panelIndex==="number"?p.panels[panelIndex]:undefined;setBusy("image");setBusyTarget(panel?`${p.pageNumber}-${panelIndex}`:`${p.pageNumber}`);setError("");try{const imageData=await visualImage(project,p,panel);setProject(c=>{if(!c)return c;return{...c,updatedAt:new Date().toISOString(),pages:c.pages.map((x,i)=>i!==pageIndex?x:typeof panelIndex!=="number"?{...x,imageData}:{...x,panels:x.panels.map((q,n)=>n===panelIndex?{...q,imageData}:q)})}})}catch(x){setError(message(x,"This image could not be generated."))}finally{setBusy("");setBusyTarget("")}}
  async function generateAll(){if(!project)return;setBusy("all-images");setError("");let working=project;try{for(let i=0;i<working.pages.length;i++){const p=working.pages[i];if(working.mode==="comic"){for(let n=0;n<p.panels.length;n++){if(working.pages[i].panels[n].imageData)continue;setBusyTarget(`${p.pageNumber}-${n}`);const imageData=await visualImage(working,p,p.panels[n]);const panels=working.pages[i].panels.map((x,j)=>j===n?{...x,imageData}:x);working={...working,updatedAt:new Date().toISOString(),pages:working.pages.map((x,j)=>j===i?{...x,panels}:x)};setProject(working)}}else if(!p.imageData){setBusyTarget(`${p.pageNumber}`);const imageData=await visualImage(working,p);working={...working,updatedAt:new Date().toISOString(),pages:working.pages.map((x,j)=>j===i?{...x,imageData}:x)};setProject(working)}}setNotice("All page art is complete. Dialogue and captions remain editable.")}catch(x){setProject(working);setError(`${message(x,"Image generation stopped.")} Finished images were saved.`)}finally{setBusy("");setBusyTarget("")}}
  function move(dir:-1|1){if(!project||activePage===0)return;const target=activePage+dir;if(target<1||target>=project.pages.length)return;const pages=[...project.pages];[pages[activePage],pages[target]]=[pages[target],pages[activePage]];setProject({...project,updatedAt:new Date().toISOString(),pages:pages.map((x,i)=>({...x,pageNumber:i+1,role:i===0?"cover":i===pages.length-1?"cta":"content"}))});setActivePage(target)}
  async function runExport(kind:"pdf"|"zip"|"page"){if(!project||!page)return;setBusy(kind==="pdf"?"pdf":kind==="zip"?"zip":"image");try{if(kind==="pdf")await exportVisualPdf(project);if(kind==="zip")await exportVisualPagesZip(project);if(kind==="page")await exportVisualPageJpeg(project,page)}catch(x){setError(message(x,"The visual export could not be created."))}finally{setBusy("")}}
  function open(saved:VisualBookProject){setMode(saved.mode);setBrief(projectBrief(saved));setProject(saved);setActivePage(0);setNotice("Saved visual project opened.")}
  async function remove(saved:VisualBookProject){await deleteVisualProject(saved.id);void deleteCloudProject("visual",saved.id).catch(()=>setSyncState("local-only"));setProjects(c=>c.filter(x=>x.id!==saved.id));if(project?.id===saved.id)reset()}

  return <div className="visual-studio">
    <div className="visual-studio-header"><div><span className="eyebrow"><LayoutGrid size={18}/> Page-based creator</span><h1>Build a visual mini book.</h1><p>Five to ten designed pages with editable text, consistent art, and comic-ready panels.</p></div>{project?<button className="visual-new-button" onClick={reset}><Plus size={16}/> New visual project</button>:null}</div>
    <div className="visual-mode-switch" role="tablist"><button className={mode==="visual"?"selected":""} onClick={()=>chooseMode("visual")} disabled={locked}><FileImage size={18}/><span>Visual Mini eBook<small>Image-rich designed pages</small></span></button><button className={mode==="comic"?"selected":""} onClick={()=>chooseMode("comic")} disabled={locked}><MessageCircle size={18}/><span>Comics & Graphic Story<small>Panels, dialogue, captions</small></span></button></div>
    <div className="visual-workspace"><form className="visual-brief-panel" onSubmit={createStoryboard}>
      <Field label="Title" value={brief.title} set={v=>updateBrief("title",v)} placeholder="Your visual book title" disabled={locked||Boolean(project)}/><Field label="Subtitle (optional)" value={brief.subtitle} set={v=>project?updateProjectBrief("subtitle",v):updateBrief("subtitle",v)} placeholder="AI can create one" disabled={locked}/><Field label="Author" value={brief.author} set={v=>project?updateProjectBrief("author",v):updateBrief("author",v)} placeholder="Author name" disabled={locked}/>
      <fieldset className="visual-choice-field" disabled={locked||Boolean(project)}><legend>{mode==="comic"?"Comic format":"Mini book type"}</legend><div className="visual-choice-grid">{(mode==="comic"?COMIC_FORMATS:VISUAL_BOOK_KINDS).map(o=><button type="button" key={o.id} className={(mode==="comic"?brief.comicFormat:brief.kind)===o.id?"selected":""} onClick={()=>mode==="comic"?updateBrief("comicFormat",o.id as VisualBookBrief["comicFormat"]):updateBrief("kind",o.id as VisualBookBrief["kind"])}><strong>{o.label}</strong><small>{o.note}</small></button>)}</div></fieldset>
      <Field textarea label={mode==="comic"?"Story idea and conflict":"Story idea or core promise"} value={brief.premise} set={v=>project?updateProjectBrief("premise",v):updateBrief("premise",v)} placeholder="What should happen, change, or help the reader?" disabled={locked}/><Field label="Target reader" value={brief.audience} set={v=>project?updateProjectBrief("audience",v):updateBrief("audience",v)} placeholder="Who is this for?" disabled={locked}/>
      <fieldset className="visual-inline-options" disabled={locked||Boolean(project)}><legend>Total pages, including cover</legend><div>{([5,7,10] as VisualPageCount[]).map(n=><button type="button" key={n} className={brief.pageCount===n?"selected":""} onClick={()=>updateBrief("pageCount",n)}>{n}</button>)}</div></fieldset>
      <fieldset className="visual-inline-options" disabled={locked}><legend>Visual style</legend><select value={brief.visualStyle} onChange={e=>project?updateProjectBrief("visualStyle",e.target.value as VisualBookBrief["visualStyle"]):updateBrief("visualStyle",e.target.value as VisualBookBrief["visualStyle"])}>{VISUAL_STYLES.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></fieldset>
      <div className="character-lock-block"><div><span><Save size={15}/> Character & world lock</span><small>Used on every recurring image for consistency.</small></div><textarea rows={5} value={brief.characterBible} onChange={e=>project?updateProjectBrief("characterBible",e.target.value):updateBrief("characterBible",e.target.value)} placeholder="AI builds this if blank" disabled={locked}/><textarea rows={3} value={brief.palette} onChange={e=>project?updateProjectBrief("palette",e.target.value):updateBrief("palette",e.target.value)} placeholder="Palette and lighting lock" disabled={locked}/>{project?.characterBible?<b><Check size={14}/> Character design locked</b>:null}</div>
      {error?<p className="form-error">{error}</p>:null}{notice?<p className="visual-notice"><Check size={15}/>{notice}</p>:null}
      {!project?<button className="generate-button" type="submit" disabled={locked}>{busy==="storyboard"?<LoaderCircle className="spin"/>:<Sparkles/>}{busy==="storyboard"?"Designing every page":"Create editable storyboard"}</button>:<div className="visual-production-actions"><button type="button" className="visual-primary-action" onClick={generateAll} disabled={locked||imageProgress.complete===imageProgress.total}>{busy==="all-images"?<LoaderCircle className="spin"/>:<ImageIcon/>}{busy==="all-images"?`Creating art ${imageProgress.complete+1} of ${imageProgress.total}`:imageProgress.complete===imageProgress.total?"All art complete":`Generate all art (${imageProgress.total-imageProgress.complete} remaining)`}</button><div className="visual-export-actions"><button type="button" onClick={()=>runExport("pdf")} disabled={locked}><FileText size={16}/> PDF</button><button type="button" onClick={()=>runExport("zip")} disabled={locked}><Download size={16}/> Page ZIP</button></div></div>}
    </form><div className="visual-editor-panel">{project&&page?<><div className="visual-editor-toolbar"><div><span>Storyboard</span><strong>{project.pages.length} pages · {imageProgress.complete}/{imageProgress.total} images</strong></div><div><button onClick={()=>move(-1)} disabled={locked||activePage<=1}><ChevronUp size={16}/></button><button onClick={()=>move(1)} disabled={locked||activePage===0||activePage>=project.pages.length-1}><ChevronDown size={16}/></button><button onClick={rewrite} disabled={locked}><RotateCcw size={16}/> Rewrite page</button></div></div>
      <div className="visual-page-tabs">{project.pages.map((p,i)=><button key={p.id} className={i===activePage?"selected":""} onClick={()=>setActivePage(i)}><span>{p.pageNumber}</span><small>{p.role==="cover"?"Cover":p.title}</small>{hasArt(project.mode,p)?<Check size={12}/>:null}</button>)}</div>
      <div className="visual-page-editor"><PagePreview project={project} page={page}/><div className="visual-page-controls"><div className="visual-page-meta"><span>Page {page.pageNumber}</span><small>{page.role}</small></div><Field label="Page heading" value={page.title} set={v=>updatePage({title:v})} placeholder="Page heading" disabled={locked}/><Field textarea label={project.mode==="comic"?"Page note":"Page copy"} value={page.body} set={v=>updatePage({body:v})} placeholder="Short page copy" disabled={locked}/>
        {project.mode==="visual"?<><Field textarea label="Art direction" value={page.imagePrompt} set={v=>updatePage({imagePrompt:v})} placeholder="Visible scene only" disabled={locked}/><button className="panel-image-button" type="button" onClick={()=>generateImage(activePage)} disabled={locked}>{busy==="image"&&busyTarget===String(page.pageNumber)?<LoaderCircle className="spin"/>:<ImageIcon/>}{page.imageData?"Regenerate page art":"Generate page art"}</button></>:<div className="comic-panel-editors"><div className="comic-panel-count-control"><span>{page.panels.length} panel{page.panels.length===1?"":"s"}</span>{page.panels.length<4?<button type="button" onClick={addPanel}><Plus size={13}/> Add panel</button>:null}</div>{page.panels.map((p,pi)=><section key={p.id}><header><strong>Panel {pi+1}</strong><div>{page.panels.length>1?<button className="comic-remove-panel" type="button" onClick={()=>removePanel(pi)}><Trash2 size={14}/></button>:null}<button type="button" onClick={()=>generateImage(activePage,pi)} disabled={locked}>{busy==="image"&&busyTarget===`${page.pageNumber}-${pi}`?<LoaderCircle className="spin"/>:<ImageIcon/>}{p.imageData?"Regenerate art":"Generate art"}</button></div></header><Field textarea label="Visible scene" value={p.scene} set={v=>updatePanel(pi,{scene:v})} placeholder="Characters, action, setting" disabled={locked}/><Field label="Camera" value={p.camera} set={v=>updatePanel(pi,{camera:v})} placeholder="Close-up, wide..." disabled={locked}/><Field label="Narration caption" value={p.caption} set={v=>updatePanel(pi,{caption:v})} placeholder="Optional narration" disabled={locked}/><Field label="Sound effect" value={p.soundEffect} set={v=>updatePanel(pi,{soundEffect:v})} placeholder="Optional: THUD!" disabled={locked}/><div className="dialogue-editor"><div><span>Speech bubbles</span>{p.dialogue.length<3?<button type="button" onClick={()=>addDialogue(pi)}><Plus size={13}/> Add</button>:null}</div>{p.dialogue.map((d,di)=><div className="dialogue-row" key={di}><input value={d.speaker} onChange={e=>updateDialogue(pi,di,"speaker",e.target.value)} placeholder="Speaker"/><textarea rows={2} value={d.text} onChange={e=>updateDialogue(pi,di,"text",e.target.value)} placeholder="Short dialogue"/><button type="button" onClick={()=>removeDialogue(pi,di)}><Trash2 size={14}/></button></div>)}</div></section>)}</div>}
        <button className="download-page-button" type="button" onClick={()=>runExport("page")} disabled={locked}><Download size={16}/> Download this page JPG</button></div></div></>:<div className="visual-empty-preview"><div><FileImage size={38}/><LayoutGrid size={30}/></div><span className="preview-kicker">Visual publishing</span><h2>One idea. Up to ten designed pages.</h2><p>Create and approve the page plan before image generation begins.</p><div><span>Editable text</span><span>Character lock</span><span>Page-by-page art</span></div></div>}</div></div>
    {projects.length?<section className="visual-project-library"><div><span className="eyebrow"><BookOpen size={16}/> Saved visual projects</span><small>{syncState==="synced"?"Cloud synced across devices":syncState==="syncing"?"Syncing this device...":"Saved locally; cloud sync paused"}</small></div><div>{projects.map(p=><article key={p.id}><button className="visual-project-open" onClick={()=>open(p)}><span>{p.mode==="comic"?"Comic":"Visual Mini"}</span><strong>{p.title}</strong><small>{p.pages.length} pages · {p.author}</small></button><button className="visual-project-delete" onClick={()=>void remove(p)}><Trash2 size={15}/></button></article>)}</div></section>:null}
  </div>
}

function PagePreview({project,page}:{project:VisualBookProject;page:VisualBookPage}){if(project.mode==="comic")return <div className={`visual-page-canvas comic-preview panels-${Math.min(4,Math.max(1,page.panels.length))}`}>{page.panels.map(p=><div className="comic-preview-panel" key={p.id} style={p.imageData?{backgroundImage:`url(${p.imageData})`}:undefined}>{!p.imageData?<span><ImageIcon/> Art pending</span>:null}<div className="comic-bubbles">{p.dialogue.map((d,i)=><p key={i}><b>{d.speaker}</b>{d.text}</p>)}</div>{p.caption?<small className="comic-caption">{p.caption}</small>:null}{p.soundEffect?<strong className="comic-sfx">{p.soundEffect}</strong>:null}</div>)}{page.role==="cover"?<div className="comic-cover-copy"><h2>{project.title}</h2><p>{project.subtitle}</p><small>{project.author}</small></div>:null}</div>;return <div className={`visual-page-canvas visual-layout-${page.layout}${page.role==="cover"?" visual-cover-preview":""}`}><div className="visual-preview-image" style={page.imageData?{backgroundImage:`url(${page.imageData})`}:undefined}>{!page.imageData?<span><ImageIcon/> Art pending</span>:null}</div><div className="visual-preview-copy">{page.role==="cover"?<><h2>{project.title}</h2><p>{project.subtitle}</p><small>{project.author}</small></>:<><em>{project.title}</em><h2>{page.title}</h2><p>{page.body}</p><small>{page.pageNumber}</small></>}</div></div>}
function Field({label,value,set,placeholder,textarea=false,disabled=false}:{label:string;value:string;set:(v:string)=>void;placeholder:string;textarea?:boolean;disabled?:boolean}){return <label className="field visual-field"><span>{label}</span>{textarea?<textarea value={value} onChange={e=>set(e.target.value)} placeholder={placeholder} rows={4} disabled={disabled}/>:<input value={value} onChange={e=>set(e.target.value)} placeholder={placeholder} disabled={disabled}/>}</label>}
async function api(url:string,body:unknown){const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(data.error??"The generator could not be reached. Your project is safe."));return data}
async function visualImage(project:VisualBookProject,page:VisualBookPage,panel?:ComicPanel){const data=await api("/api/visual-image",{project:projectBrief(project),page,panel});const imageData=String(data.imageData??"");if(!imageData)throw new Error("The image generator returned no usable image.");return imageData}
function projectBrief(p:VisualBookProject):VisualBookBrief{return{mode:p.mode,title:p.title,subtitle:p.subtitle,author:p.author,kind:p.kind,comicFormat:p.comicFormat,premise:p.premise,audience:p.audience,pageCount:p.pageCount,visualStyle:p.visualStyle,characterBible:p.characterBible,palette:p.palette}}
function hasArt(mode:VisualProjectMode,p:VisualBookPage){return mode==="comic"?p.panels.length>0&&p.panels.every(x=>x.imageData):Boolean(p.imageData)}
function message(x:unknown,fallback:string){return x instanceof Error?x.message:fallback}
